app/config/urls.py
from django.contrib import admin
from django.urls import path, include

from assets.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('users/', include('users.urls', namespace='users')),
]

app/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from users.views import UserLoginView, UserRegisterView, UserProfileUpdateView, UserLogoutView, UserAssetsView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', login_required(UserProfileUpdateView.as_view()), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('assets/', login_required(UserAssetsView.as_view()), name='assets'),
]

app/assets/models.py
from django.db import models
from django.contrib.auth.models import User


class Asset(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('maintenance', 'Maintenance'),
    ]

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')
    entry_date = models.DateField()

    def __str__(self):
        return self.name

app/users/models.py
from django.contrib.auth.models import User
from django.db import models

#
# class UserPasswordChange(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     new_password = models.CharField(max_length=100)

app/assets/forms.py
from django import forms


class AssetFilterForm(forms.Form):
    name = forms.CharField(max_length=200, required=False)
    status = forms.CharField(max_length=100, required=False)
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)

app/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1',
                  'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

app/assets/views.py
from django.views.generic.base import TemplateView


class IndexTemplateView(TemplateView):
    template_name = 'assets/index.html'

app/users/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin

from assets.models import Asset
from users.forms import UserLoginForm, UserRegisterForm, UserProfileForm
from users.models import User


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    authentication_form = UserLoginForm

    def get_context_data(self, **kwargs):
        context = super(UserLoginView, self).get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context


class UserRegisterView(SuccessMessageMixin, CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def get_context_data(self, object_list=None, **kwargs):
        context = super(UserRegisterView, self).get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context


class UserProfileUpdateView(SuccessMessageMixin, UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = UserProfileForm
    success_message = 'Изменения сохранены!'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))

    def get_context_data(self, **kwargs):
        context = super(UserProfileUpdateView, self).get_context_data(**kwargs)
        context['password_change_form'] = PasswordChangeForm(self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        password_change_form = PasswordChangeForm(self.request.user, request.POST)

        if form.is_valid() and password_change_form.is_valid():
            new_password = password_change_form.cleaned_data['new_password1']
            self.request.user.set_password(new_password)
            self.request.user.save()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class UserLogoutView(LogoutView):
    template_name = 'users/login.html'


class UserAssetsView(LoginRequiredMixin, TemplateView):
    template_name = 'users/assets.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        assets = Asset.objects.filter(owner=user)
        context['assets'] = assets
        return context

app/assets/templates/assets/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assets</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'users:profile' user.id %}">Profile</a></li>
                    <li><a href="{% url 'users:assets'%}">Assets</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <!-- Footer content here -->
    </footer>
</body>
</html>

app/assets/templates/assets/index.html
{% extends 'assets/base.html' %}

{% block content %}
  <h2>Welcome to the Home Page</h2>
  {% if user.is_authenticated %}
    <p>You are logged in as: {{ user.username }}</p>
  {% else %}
    <p>You are not logged in.</p>
  {% endif %}
{% endblock %}

app/users/templates/users/assets.html
{% extends 'users/base.html' %}

{% block content %}
  <h2>My Assets</h2>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Entry Date</th>
      </tr>
    </thead>
    <tbody>
      {% for asset in assets %}
        <tr>
          <td>{{ asset.name }}</td>
          <td>{{ asset.status }}</td>
          <td>{{ asset.entry_date }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

app/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <p>Don't have an account? <a href="{% url 'users:register' %}">Register</a></p>
{% endblock %}

app/users/templates/users/profile.html
{% extends 'users/base.html' %}

{% block content %}
  <h2>User Profile</h2>
  <p>Username: {{ user.username }}</p>
  <p>Email: {{ user.email }}</p>
  <p>First Name: {{ user.first_name }}</p>
  <p>Last Name: {{ user.last_name }}</p>

  <h3>Change Password</h3>
  <form method="post">
    {% csrf_token %}
    {{ password_change_form.as_p }}
    <button type="submit">Change Password</button>
  </form>
{% endblock %}

app/users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}